### ISSUE TITLE
modify posmatrix to bedgraph

### ISSUE THREAD

**Issue by cmdoret** [baudrly/hicstuff#1]
Slightly modifying the output format produced when using the --posmatrix flag of yahcp to generate a bedgraph file as follows:

| chromA | startA | endA | chromB | startB | endB | count |
|--|--|--|--|--|--|--|

This file format is compatible with  [cooler](https://cooler.readthedocs.io/en/latest/datamodel.html) and can be directly converted to binary format.

**Comment by baudrly** [comment]
So endA will just be the following line's 'startA', am I correct?

**Comment by cmdoret** [comment]
Not necessarily, the file is still a sparse matrix representation (upper triangle only). If binA = chromA startA endA, the file will be structured as follows. 

| | | |
|-|-|-|
| binA | binA | count |
| binA | binB | count |
| binA | binC | count |
| binB | binB | count |
| binB | binC | count |

The content of the file would not change, the formatting would. Makes sense ?
This is not actual bedGraph format, but "a 2D extension" of it, according to cooler's doc, sorry for the confusion.

**Comment by cmdoret** [comment]
Added this in b073b1e6b5105dd2a83639f6c26e373a79def776
